# TravisCI configuration for stevegrunwell/wp-admin-tabbed-settings-pages

language: php
os:
  - linux
dist: xenial

services:
    - mysql

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - "${HOME}/.composer/cache"

php:
  - 7.4
  - 7.3
  - 7.2
  - 7.1

env:
  - WP_VERSION=latest

jobs:
  fast_finish: true
  include:
    - name: "Check Composer configuration"
      php: 7.4
      install: skip
      script:
        - composer validate --strict
    - name: "Coding standards"
      php: 7.4
      install:
        - composer install --prefer-dist --no-interaction --no-suggest
      script:
        # Run PHP_CodeSniffer
        - composer test:standards
    - name: "Bleeding edge"
      php: 7.4
      env: WP_VERSION=trunk
  allow_failures:
    - name: Bleeding edge

before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug.ini does not exist"

install:
  - composer install --prefer-dist --no-interaction --no-suggest
  - vendor/bin/install-wp-tests.sh wordpress_test root "" localhost "${WP_VERSION}"

script:
  # Run PHPUnit
  - composer test:unit
  - WP_MULTISITE=1 composer test:unit
